"""v1 core tables

Revision ID: ef4ea0fe1f20
Revises: 
Create Date: 2026-09-28 07:27:22.116793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_source_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_runs_source'), ['source'], unique=False)

    op.create_table('mandis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('coords_verified', sa.Boolean(), nullable=False),
    sa.Column('geofence_radius_m', sa.Float(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('arrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tonnes', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'commodity', 'date', 'source')
    )
    with op.batch_alter_table('arrivals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arrivals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_arrivals_mandi_id'), ['mandi_id'], unique=False)

    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('spike_prob', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('trained_on_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'commodity', 'issue_date', 'horizon_weeks', 'model_name')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_mandi_id'), ['mandi_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('variety', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'commodity', 'variety', 'grade', 'date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_commodity'), ['commodity'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_mandi_id'), ['mandi_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('mandi_id', sa.Integer(), nullable=True),
    sa.Column('preferred_lang', sa.String(length=5), nullable=False),
    sa.Column('watch_mandi_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_org_id'), ['org_id'], unique=False)

    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('rh_pct', sa.Float(), nullable=True),
    sa.Column('solar_kwh_m2', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'date', 'source')
    )
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_mandi_id'), ['mandi_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_org_id'), ['org_id'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('lender_org_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('quantity_tons', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('pickup_label', sa.String(length=200), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lon', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivered_weight_kg', sa.Float(), nullable=True),
    sa.Column('sale_price_per_quintal', sa.Float(), nullable=True),
    sa.Column('payout_status', sa.String(length=16), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lender_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('fleet_org_id', sa.Integer(), nullable=True),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('load_tons', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_qr_token', sa.String(length=64), nullable=False),
    sa.Column('delivery_qr_token', sa.String(length=64), nullable=False),
    sa.Column('pickup_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_distance_km', sa.Float(), nullable=True),
    sa.Column('planned_duration_min', sa.Float(), nullable=True),
    sa.Column('route_geometry', sa.JSON(), nullable=True),
    sa.Column('route_source', sa.String(length=16), nullable=False),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lon', sa.Float(), nullable=True),
    sa.Column('last_speed_kmph', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remaining_km', sa.Float(), nullable=True),
    sa.Column('eta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fleet_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_qr_token'),
    sa.UniqueConstraint('pickup_qr_token'),
    sa.UniqueConstraint('share_token')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_fleet_org_id'), ['fleet_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_mandi_id'), ['mandi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('geofence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofence_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofence_events_trip_id'), ['trip_id'], unique=False)

    op.create_table('gps_points',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'recorded_at')
    )
    # ### end Alembic commands ###
    _postgres_extras()


def _postgres_extras() -> None:
    """PostGIS geography columns + GiST indexes and a TimescaleDB hypertable.
    Skipped on SQLite (tests) and skipped individually if an extension is missing."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    available = {r[0] for r in bind.exec_driver_sql("SELECT name FROM pg_available_extensions")}
    if "postgis" in available:
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        for table, lat, lon in (("mandis", "lat", "lon"), ("gps_points", "lat", "lon"), ("lots", "pickup_lat", "pickup_lon")):
            op.execute(
                f"ALTER TABLE {table} ADD COLUMN geog geography(Point, 4326) "
                f"GENERATED ALWAYS AS (CASE WHEN {lat} IS NULL OR {lon} IS NULL THEN NULL "
                f"ELSE ST_SetSRID(ST_MakePoint({lon}, {lat}), 4326)::geography END) STORED"
            )
            op.execute(f"CREATE INDEX ix_{table}_geog ON {table} USING GIST (geog)")
    if "timescaledb" in available:
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute("SELECT create_hypertable('gps_points', 'recorded_at', migrate_data => true, if_not_exists => true)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_points')
    with op.batch_alter_table('geofence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofence_events_trip_id'))

    op.drop_table('geofence_events')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_trips_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_trips_fleet_org_id'))
        batch_op.drop_index(batch_op.f('ix_trips_driver_id'))

    op.drop_table('trips')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_lots_org_id'))
        batch_op.drop_index(batch_op.f('ix_lots_farmer_id'))

    op.drop_table('lots')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_org_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_weather_date'))

    op.drop_table('weather')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_org_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_prices_date'))
        batch_op.drop_index(batch_op.f('ix_prices_commodity'))

    op.drop_table('prices')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_issue_date'))

    op.drop_table('forecasts')
    with op.batch_alter_table('arrivals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arrivals_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_arrivals_date'))

    op.drop_table('arrivals')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('mandis')
    with op.batch_alter_table('data_source_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_runs_source'))

    op.drop_table('data_source_runs')
    # ### end Alembic commands ###
