"""weather forecast archive

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 11:36:07.232401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('rh_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'issued_on', 'target_date', 'source')
    )
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_forecasts_issued_on'), ['issued_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_forecasts_mandi_id'), ['mandi_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_forecasts_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_weather_forecasts_issued_on'))

    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
