"""graph edges

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 14:48:50.292061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('src_mandi_id', sa.Integer(), nullable=False),
    sa.Column('dst_mandi_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('km', sa.Float(), nullable=True),
    sa.Column('distance_source', sa.String(length=20), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('flow_index', sa.Float(), nullable=True),
    sa.Column('data_provenance', sa.String(length=20), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['src_mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'src_mandi_id', 'dst_mandi_id', 'edge_type')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_dst_mandi_id'), ['dst_mandi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_src_mandi_id'), ['src_mandi_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_src_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_dst_mandi_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_build_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_as_of'))

    op.drop_table('graph_edges')
    # ### end Alembic commands ###
