"""satellite obs

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 15:40:58.483863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_obs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('scene_id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tile', sa.String(length=20), nullable=True),
    sa.Column('baseline', sa.String(length=10), nullable=True),
    sa.Column('scene_cloud_pct', sa.Float(), nullable=True),
    sa.Column('cropland_px', sa.Integer(), nullable=False),
    sa.Column('in_scene_px', sa.Integer(), nullable=False),
    sa.Column('clear_px', sa.Integer(), nullable=False),
    sa.Column('clear_frac', sa.Float(), nullable=False),
    sa.Column('ndvi_median', sa.Float(), nullable=True),
    sa.Column('ndvi_mean', sa.Float(), nullable=True),
    sa.Column('ndvi_p25', sa.Float(), nullable=True),
    sa.Column('ndvi_p75', sa.Float(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'district')
    )
    with op.batch_alter_table('satellite_obs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satellite_obs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_satellite_obs_district'), ['district'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellite_obs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satellite_obs_district'))
        batch_op.drop_index(batch_op.f('ix_satellite_obs_date'))

    op.drop_table('satellite_obs')
    # ### end Alembic commands ###
