"""forecast calibration

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 05:35:35.890255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibration', sa.String(length=24), server_default='none', nullable=False))
        batch_op.add_column(sa.Column('p10_raw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('p90_raw', sa.Float(), nullable=True))

    # ### end Alembic commands ###
    # existing forecasts were never calibrated: their range IS the model's raw range
    op.execute("UPDATE forecasts SET p10_raw = p10, p90_raw = p90, calibration = 'none'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_column('p90_raw')
        batch_op.drop_column('p10_raw')
        batch_op.drop_column('calibration')

    # ### end Alembic commands ###
