"""load proposals

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-30 08:04:07.430501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """V3-1: optimizer proposals (shared loads, return loads) that a person accepts or rejects."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('est_saving', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_provenance', sa.String(length=16), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('load_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_load_proposals_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_proposals_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_proposals_org_id'))
        batch_op.drop_index(batch_op.f('ix_load_proposals_kind'))

    op.drop_table('load_proposals')
    # ### end Alembic commands ###
