"""scenario runs

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-30 10:18:22.038496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """V3-2: scenario-simulator runs (COUNTERFACTUAL ESTIMATES), kept apart from forecasts."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('forecast_issue_date', sa.Date(), nullable=True),
    sa.Column('data_provenance', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_runs_scenario'), ['scenario'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_runs_scenario'))

    op.drop_table('scenario_runs')
    # ### end Alembic commands ###
